server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.100.164.30:23306/test?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 10.100.164.30
    port: 26379
  application:
    name: docker-demo